/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package mobi.timon.enc/go */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */



















#line 3 "utils.go"
 #include <stdlib.h>

#line 1 "cgo-generated-wrapper"



/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* AesGcmEncrypt(char* plaintext, int plaintextLen, char* key, int keyLen, int* outLen);
extern char* AesGcmDecrypt(char* ciphertext, int ciphertextLen, char* key, int keyLen, int* outLen);
extern char* Argon2idHash(char* password, int passwordLen, char* salt, int saltLen, int timeCost, int memoryCost, int parallelism, int keyLen, int* outLen);
extern char* BcryptHash(char* password, int passwordLen, int cost, int* outLen);
extern char* BcryptVerify(char* password, int passwordLen, char* hash, int hashLen, int* outLen);
extern char* AesCbcEncrypt(char* plaintext, int plaintextLen, char* key, int keyLen, int* outLen);
extern char* AesCbcDecrypt(char* ciphertext, int ciphertextLen, char* key, int keyLen, int* outLen);
extern char* ChaCha20Poly1305Encrypt(char* plaintext, int plaintextLen, char* key, int keyLen, int* outLen);
extern char* ChaCha20Poly1305Decrypt(char* ciphertext, int ciphertextLen, char* key, int keyLen, int* outLen);
extern char* DesCbcEncrypt(char* plaintext, int plaintextLen, char* key, int keyLen, int* outLen);
extern char* DesCbcDecrypt(char* ciphertext, int ciphertextLen, char* key, int keyLen, int* outLen);
extern char* EcdsaGenerateKey(int curve, int* outLen);
extern char* EcdsaSign(char* message, int messageLen, char* privateKey, int privateKeyLen, int* outLen);
extern char* EcdsaVerify(char* message, int messageLen, char* signature, int signatureLen, char* publicKey, int publicKeyLen, int* outLen);
extern char* EcdsaPrivateKeyToPublicKey(char* privateKey, int privateKeyLen, int* outLen);
extern char* Ed25519GenerateKey(int* outLen);
extern char* Ed25519Sign(char* message, int messageLen, char* privateKey, int privateKeyLen, int* outLen);
extern char* Ed25519Verify(char* message, int messageLen, char* signature, int signatureLen, char* publicKey, int publicKeyLen, int* outLen);
extern char* Sha1(char* data, int dataLen, int* outLen);
extern char* Sha256(char* data, int dataLen, int* outLen);
extern char* Blake2b256(char* data, int dataLen, int* outLen);
extern char* Md5(char* data, int dataLen, int* outLen);
extern char* HmacSha256(char* data, int dataLen, char* key, int keyLen, int* outLen);
extern char* HmacSha512(char* data, int dataLen, char* key, int keyLen, int* outLen);
extern char* Scrypt(char* password, int passwordLen, char* salt, int saltLen, int keyLen, int* outLen);
extern char* Pbkdf2(char* password, int passwordLen, char* salt, int saltLen, int iterations, int keyLen, int* outLen);
extern char* Hkdf(char* ikm, int ikmLen, char* salt, int saltLen, char* info, int infoLen, int keyLen, int* outLen);
extern char* RandomBytes(int length, int* outLen);
extern char* RsaGenerateKey(int bits, int* outLen);
extern char* RsaEncrypt(char* plaintext, int plaintextLen, char* publicKey, int publicKeyLen, int* outLen);
extern char* RsaDecrypt(char* ciphertext, int ciphertextLen, char* privateKey, int privateKeyLen, int* outLen);
extern char* RsaSign(char* message, int messageLen, char* privateKey, int privateKeyLen, int* outLen);
extern char* RsaVerify(char* message, int messageLen, char* signature, int signatureLen, char* publicKey, int publicKeyLen, int* outLen);
extern char* RsaPrivateKeyToPublicKey(char* privateKey, int privateKeyLen, int* outLen);
extern char* Sha512(char* data, int dataLen, int* outLen);
extern char* AesCtrEncrypt(char* plaintext, int plaintextLen, char* key, int keyLen, int* outLen);
extern char* AesCtrDecrypt(char* ciphertext, int ciphertextLen, char* key, int keyLen, int* outLen);
extern char* ChaCha20Encrypt(char* plaintext, int plaintextLen, char* key, int keyLen, int* outLen);
extern char* ChaCha20Decrypt(char* ciphertext, int ciphertextLen, char* key, int keyLen, int* outLen);
extern void FreeBytes(void* ptr);
extern char* AesXtsEncrypt(char* plaintext, int plaintextLen, char* key, int keyLen, long long sectorNum, int* outLen);
extern char* AesXtsDecrypt(char* ciphertext, int ciphertextLen, char* key, int keyLen, long long sectorNum, int* outLen);

#ifdef __cplusplus
}
#endif
