import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

// :crypto — KMP 加密库（Rust core via JNI/cinterop）。
// Android: JNI → libencrust.so（cargo-ndk 构建 4 ABI）
// Apple: cinterop → libencrust.a（cargo 构建各 Apple target）
plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.library)
    `maven-publish`
}

kotlin {
    applyDefaultHierarchyTemplate()

    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    androidTarget {
        compilerOptions { jvmTarget = JvmTarget.JVM_11 }
    }

    // Apple targets
    iosArm64()
    iosSimulatorArm64()
    macosArm64()
    macosX64()

    // cinterop for each Apple target
    fun KotlinNativeTarget.cryptoCInterop() {
        compilations["main"].cinterops {
            val cryptoNative by creating {
                includeDirs.headerFilterOnly(project.file("src/nativeInterop/cinterop"))
                tasks[interopProcessingTaskName].dependsOn("buildRustApple")
            }
        }
    }

    // 构建前把 .def 的绝对路径 placeholder 替换为当前机器的 cargo target 路径。
    // 这样本地 macOS 开发和 CI macos-latest runner 都不需要手改 def。
    val defFile = file("src/nativeInterop/cinterop/cryptoNative.def")
    tasks.register("writeCryptoCInteropDef") {
        val rustRoot = file("../rust").absolutePath
        val defBody = buildString {
            appendLine("package = mobi.timon.crypto.native")
            appendLine()
            appendLine("headers = encrust.h")
            appendLine("headerFilter = encrust.h")
            appendLine()
            appendLine("# Auto-generated by Gradle (build.gradle.kts writeCryptoCInteropDef task)")
            appendLine("# Updates absolute paths to point at THIS machine's cargo target dir.")
            appendLine()
            listOf(
                "ios_arm64" to "$rustRoot/target/aarch64-apple-ios/release",
                "ios_simulator_arm64" to "$rustRoot/target/aarch64-apple-ios-sim/release",
                "ios_x64" to "$rustRoot/target/x86_64-apple-ios/release",
            "ios_macos_simulator_arm64" to "$rustRoot/target/aarch64-apple-ios-macabi/release",
                "macos_arm64" to "$rustRoot/target/aarch64-apple-darwin/release",
                "macos_x64" to "$rustRoot/target/x86_64-apple-darwin/release",
                "tvos_arm64" to "$rustRoot/target/aarch64-apple-tvos/release",
                "watchos_arm64" to "$rustRoot/target/aarch64_32-apple-watchos/release",
            ).forEach { (target, libPath) ->
                appendLine("staticLibraries.$target = libencrust.a")
                appendLine("libraryPaths.$target = $libPath")
                appendLine()
            }
        }
        inputs.property("defBody", defBody)
        outputs.file(defFile)
        doLast {
            defFile.parentFile.mkdirs()
            defFile.writeText(defBody)
        }
    }

    // writeDef 在 cinterop 创建前写好绝对路径
    tasks.matching { it.name == "writeCryptoCInteropDef" }.configureEach {
        dependsOn("buildRustApple")
        mustRunAfter("buildRustApple")
    }
    listOf("iosArm64", "iosSimulatorArm64", "macosArm64", "macosX64").forEach { t ->
        tasks.matching { it.name == "cinteropCryptoNative${t.replaceFirstChar { it.uppercase() }}" }
            .configureEach { dependsOn("writeCryptoCInteropDef") }
    }
    // 强制 metadata target 走 iosSimulatorArm64 的 cinterop（KMP 默认只挑一个 host target）
    tasks.matching { it.name == "compileAppleMainKotlinMetadata" }.configureEach {
        dependsOn("cinteropCryptoNativeIosSimulatorArm64")
    }
    iosArm64 { cryptoCInterop() }
    iosSimulatorArm64 { cryptoCInterop() }
    macosArm64 { cryptoCInterop() }
    macosX64 { cryptoCInterop() }
    // tvOS/watchOS targets omitted — Rust stable doesn't support them

    sourceSets {
        commonMain.dependencies {
            implementation(kotlin("stdlib"))
        }
    }
}

android {
    namespace = "mobi.timon.crypto"
    compileSdk = 36

    defaultConfig {
        minSdk = 33
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86", "x86_64")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    sourceSets["main"].jniLibs.srcDirs("src/androidMain/jniLibs")
}

// ── Rust build tasks ──────────────────────────────────────────

fun runCargo(dir: File, ndkHome: String?, args: List<String>) {
    val pb = ProcessBuilder(listOf("cargo") + args)
        .directory(dir)
        .inheritIO()
    if (ndkHome != null) pb.environment()["ANDROID_NDK_HOME"] = ndkHome
    pb.environment()["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
    // release profile 默认有 -D warnings；CI 严格模式下会触发 warnings-as-errors。
    // 关掉该 deny 防止 cargo-ndk 编出的 warning（如 jni bridge 内部）误报。
    pb.environment()["RUSTFLAGS"] = System.getenv("RUSTFLAGS") ?: "-A warnings"
    val rc = pb.start().waitFor()
    if (rc != 0) throw GradleException("cargo ${args.joinToString(" ")} failed with exit code $rc")
}



val rustDir = file("../rust")
val ndkHome = System.getenv("ANDROID_NDK_HOME")
    ?: file("${System.getProperty("user.home")}/Library/Android/sdk/ndk").takeIf { it.exists() }
        ?.listFiles()?.maxOrNull()?.toString()

// Android: cargo-ndk build for 4 ABIs → libencrust.so
val buildRustAndroid by tasks.registering {
    group = "build"
    val abis = mapOf(
        "arm64-v8a" to "aarch64-linux-android",
        "armeabi-v7a" to "armv7-linux-androideabi",
        "x86" to "i686-linux-android",
        "x86_64" to "x86_64-linux-android",
    )
    doLast {
        println("[buildRustAndroid] ndkHome=${ndkHome ?: "<unset>"}")
        abis.forEach { (abi, target) ->
            val outDir = file("src/androidMain/jniLibs/$abi")
            outDir.mkdirs()
            runCargo(rustDir, ndkHome, listOf("ndk", "-t", target, "-P", "33", "build", "--release", "--features", "jni-bridge"))
            project.copy {
                from(rustDir.resolve("target/$target/release/libencrust.so"))
                into(outDir)
            }
        }
    }
}

// Apple: cargo build for each Apple target → libencrust.a
val buildRustApple by tasks.registering {
    group = "build"
    val targets = listOf(
        "aarch64-apple-ios",
        "aarch64-apple-ios-sim",
        "aarch64-apple-darwin",
        "x86_64-apple-darwin",
        // tvos/watchOS omitted — Rust stable doesn't support them

    )
    doLast {
        targets.forEach { target ->
            runCargo(rustDir, null, listOf("build", "--release", "--target", target))
        }
    }
}

// Ensure native libs are built before Android assemble
tasks.named("preBuild") { dependsOn("buildRustAndroid") }

// ── Maven publish ─────────────────────────────────────────────

// 仅发布 Android AAR 到 GitHub Packages（KMP metadata/Apple targets 在 v2.0.0 暂不发布）。
android {
    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}
// AGP 默认发布 release variant 到 MavenPublication "release"。
// artifacts id 默认由 android.namespace 派生（"mobi.timon.crypto:crypto-android"）。
// 版本由项目 version 控制；这里显式给 Maven 坐标（KMP plugin 覆盖时不会自动生成 "release"）。
publishing {
    publications {
        register<MavenPublication>("release") {
            groupId = "mobi.timon.crypto"
            artifactId = "crypto-android"
            version = "2.0.0"
        }
    }
}
publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/ic-timon/crypto")
            credentials {
                username = providers.gradleProperty("gpr.user").orNull ?: System.getenv("GITHUB_ACTOR")
                password = providers.gradleProperty("gpr.token").orNull ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

// 诊断：打印 source sets
tasks.register("printSourceSets") {
    doLast {
        kotlin.sourceSets.forEach { ss ->
            println("SS: ${ss.name} -> ${ss.kotlin.srcDirs}")
        }
    }
}

dependencies {
    "androidTestImplementation"(libs.junit)
    "androidTestImplementation"(libs.androidx.junit)
    "androidTestImplementation"(libs.androidx.runner.alias)
    "androidTestImplementation"(libs.kotlin.testJunit)
}
