import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

// :crypto — KMP 加密库（Rust core via JNI/cinterop）。
// Android: JNI → libencrust.so（cargo-ndk 构建 4 ABI）
// Apple: cinterop → libencrust.a（cargo 构建各 Apple target）
plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    `maven-publish`
}

kotlin {
    applyDefaultHierarchyTemplate()

    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    androidTarget {
        compilerOptions { jvmTarget = JvmTarget.JVM_11 }
    }

    // Apple targets
    iosArm64()
    iosSimulatorArm64()
    macosArm64()
    macosX64()

    // cinterop for each Apple target
    fun KotlinNativeTarget.cryptoCInterop() {
        compilations["main"].cinterops {
            val cryptoNative by creating {
                includeDirs.headerFilterOnly(project.file("src/nativeInterop/cinterop"))
                tasks[interopProcessingTaskName].dependsOn("buildRustApple")
            }
        }
    }

    // 构建前把 .def 的绝对路径 placeholder 替换为当前机器的 cargo target 路径。
    // 这样本地 macOS 开发和 CI macos-latest runner 都不需要手改 def。
    val defFile = file("src/nativeInterop/cinterop/cryptoNative.def")
    tasks.register("writeCryptoCInteropDef") {
        val rustRoot = file("../rust").absolutePath
        val defBody = buildString {
            appendLine("package = mobi.timon.crypto.native")
            appendLine()
            appendLine("headers = encrust.h")
            appendLine("headerFilter = encrust.h")
            appendLine()
            appendLine("# Auto-generated by Gradle (build.gradle.kts writeCryptoCInteropDef task)")
            appendLine("# Updates absolute paths to point at THIS machine's cargo target dir.")
            appendLine()
            listOf(
                "ios_arm64" to "$rustRoot/target/aarch64-apple-ios/release",
                "ios_simulator_arm64" to "$rustRoot/target/aarch64-apple-ios-sim/release",
                "ios_x64" to "$rustRoot/target/x86_64-apple-ios/release",
            "ios_macos_simulator_arm64" to "$rustRoot/target/aarch64-apple-ios-macabi/release",
                "macos_arm64" to "$rustRoot/target/aarch64-apple-darwin/release",
                "macos_x64" to "$rustRoot/target/x86_64-apple-darwin/release",
                "tvos_arm64" to "$rustRoot/target/aarch64-apple-tvos/release",
                "watchos_arm64" to "$rustRoot/target/aarch64_32-apple-watchos/release",
            ).forEach { (target, libPath) ->
                appendLine("staticLibraries.$target = libencrust.a")
                appendLine("libraryPaths.$target = $libPath")
                appendLine()
            }
        }
        inputs.property("defBody", defBody)
        outputs.file(defFile)
        doLast {
            defFile.parentFile.mkdirs()
            defFile.writeText(defBody)
        }
    }

    // writeDef 在 cinterop 创建前写好绝对路径
    tasks.matching { it.name == "writeCryptoCInteropDef" }.configureEach {
        dependsOn("buildRustApple")
        mustRunAfter("buildRustApple")
    }
    listOf("iosArm64", "iosSimulatorArm64", "macosArm64", "macosX64").forEach { t ->
        tasks.matching { it.name == "cinteropCryptoNative${t.replaceFirstChar { it.uppercase() }}" }
            .configureEach { dependsOn("writeCryptoCInteropDef") }
    }
    // 强制 metadata target 走 iosSimulatorArm64 的 cinterop（KMP 默认只挑一个 host target）
    tasks.matching { it.name == "compileAppleMainKotlinMetadata" }.configureEach {
        dependsOn("cinteropCryptoNativeIosSimulatorArm64")
    }
    iosArm64 { cryptoCInterop() }
    iosSimulatorArm64 { cryptoCInterop() }
    macosArm64 { cryptoCInterop() }
    macosX64 { cryptoCInterop() }
    // tvOS/watchOS targets omitted — Rust stable doesn't support them

    sourceSets {
        commonMain.dependencies {
            implementation(kotlin("stdlib"))
        }
    }
}

android {
    namespace = "mobi.timon.crypto"
    compileSdk = 36

    defaultConfig {
        minSdk = 33
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86", "x86_64")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    sourceSets["main"].jniLibs.srcDirs("src/androidMain/jniLibs")
}

// ── Rust build tasks（:argon2 同款 Exec + shell 脚本模式，config-cache 安全）──
// bash -l 加载登录 shell → ~/.cargo/bin 进 PATH。

// Android: cargo-ndk 编 4 ABI → jniLibs
val buildRustAndroid by tasks.registering(Exec::class) {
    group = "build"
    workingDir = projectDir
    commandLine("bash", "-l", "build-android.sh")
}

// Apple: cargo build 4 target → libencrust.a（cinterop 静态链）
val buildRustApple by tasks.registering(Exec::class) {
    group = "build"
    workingDir = projectDir
    commandLine("bash", "-l", "build-apple.sh")
}

// Host（JVM 单测用）：cargo build 本机 target → libencrust.dylib/.so（带 jni-bridge 符号）
// 供 :shared/:nostr 的 testDebugUnitTest 在 JVM 上 System.loadLibrary("encrust")。
val buildRustHost by tasks.registering(Exec::class) {
    group = "build"
    workingDir = projectDir
    commandLine("bash", "-l", "build-host.sh")
}

// Ensure native libs are built before Android assemble
tasks.named("preBuild") { dependsOn("buildRustAndroid") }

// ── Maven publish ─────────────────────────────────────────────

// 仅发布 Android AAR 到 GitHub Packages（KMP metadata/Apple targets 在 v2.0.0 暂不发布）。
android {
    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}
// AGP 默认发布 release variant 到 MavenPublication "release"。
// artifacts id 默认由 android.namespace 派生（"mobi.timon.crypto:crypto-android"）。
// 版本由项目 version 控制；这里显式给 Maven 坐标（KMP plugin 覆盖时不会自动生成 "release"）。
publishing {
    publications {
        register<MavenPublication>("release") {
            groupId = "mobi.timon.crypto"
            artifactId = "crypto-android"
            version = "2.0.0"
        }
    }
}
publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/ic-timon/crypto")
            credentials {
                username = providers.gradleProperty("gpr.user").orNull ?: System.getenv("GITHUB_ACTOR")
                password = providers.gradleProperty("gpr.token").orNull ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

// 诊断：打印 source sets
tasks.register("printSourceSets") {
    doLast {
        kotlin.sourceSets.forEach { ss ->
            println("SS: ${ss.name} -> ${ss.kotlin.srcDirs}")
        }
    }
}

dependencies {
    // 字符串坐标（不依赖 version catalog）——本模块被 CalmClient include 时用的是宿主 catalog，
    // 宿主与 crypto 仓各自的 catalog 条目名不一致；字符串坐标两边都能构建。
    "androidTestImplementation"("junit:junit:4.13.2")
    "androidTestImplementation"("androidx.test.ext:junit:1.3.0")
    "androidTestImplementation"("androidx.test:runner:1.6.2")
    "androidTestImplementation"(kotlin("test-junit"))
}
