#ifndef ENCRUST_H
#define ENCRUST_H

/* Auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * 生成随机 secp256k1 私钥（32 字节）。
 */
 uint8_t *Secp256k1GenerateKey(int *out_len) ;

/**
 * 从私钥派生公钥。compressed=1 → 33B，=0 → 65B。
 */
 uint8_t *Secp256k1PrivateKeyToPublicKey(const uint8_t *private_key, int private_key_len, int compressed, int *out_len) ;

/**
 * ECDSA 签名。出 65B compact（r‖s‖recoveryId）。
 */
 uint8_t *Secp256k1Sign(const uint8_t *message, int message_len, const uint8_t *private_key, int private_key_len, int *out_len) ;

/**
 * ECDSA 验签。接受 65B compact（r‖s‖recoveryId）或 64B compact（r‖s）。
 */
 uint8_t *Secp256k1Verify(const uint8_t *message, int message_len, const uint8_t *signature, int signature_len, const uint8_t *public_key, int public_key_len, int *out_len) ;

/**
 * 从签名恢复公钥。输入 65B compact + 消息。
 */
 uint8_t *Secp256k1RecoverPublicKey(const uint8_t *message, int message_len, const uint8_t *signature, int signature_len, int compressed, int *out_len) ;

/**
 * BIP-340 Schnorr 签名。消息先 SHA-256。出 64B。
 */
 uint8_t *SchnorrSign(const uint8_t *message, int message_len, const uint8_t *private_key, int private_key_len, int *out_len) ;

/**
 * BIP-340 Schnorr 验签。消息先 SHA-256。publicKey 32B x-only。
 */
 uint8_t *SchnorrVerify(const uint8_t *message, int message_len, const uint8_t *signature, int signature_len, const uint8_t *public_key, int public_key_len, int *out_len) ;

/**
 * 从私钥派生 x-only 公钥（32B）。
 */
 uint8_t *SchnorrPrivateKeyToPublicKey(const uint8_t *private_key, int private_key_len, int *out_len) ;

/**
 * Schnorr 对 32B hash 直接签名（Nostr event id 用）。
 */
 uint8_t *SchnorrSignHash(const uint8_t *hash, int hash_len, const uint8_t *private_key, int private_key_len, int *out_len) ;

/**
 * Schnorr 对 32B hash 直接验签。
 */
 uint8_t *SchnorrVerifyHash(const uint8_t *hash, int hash_len, const uint8_t *signature, int signature_len, const uint8_t *public_key, int public_key_len, int *out_len) ;

 uint8_t *Sha1(const uint8_t *data, int data_len, int *out_len) ;

 uint8_t *Sha256(const uint8_t *data, int data_len, int *out_len) ;

 uint8_t *Sha384(const uint8_t *data, int data_len, int *out_len) ;

 uint8_t *Sha512(const uint8_t *data, int data_len, int *out_len) ;

 uint8_t *Blake2b256(const uint8_t *data, int data_len, int *out_len) ;

 uint8_t *Md5(const uint8_t *data, int data_len, int *out_len) ;

 uint8_t *Ripemd160(const uint8_t *data, int data_len, int *out_len) ;

 uint8_t *Keccak256(const uint8_t *data, int data_len, int *out_len) ;

 uint8_t *Keccak512(const uint8_t *data, int data_len, int *out_len) ;

/**
 * SHA-512/256（SHA-512 with different IV，截断 256 位）。
 */
 uint8_t *Sha512_256(const uint8_t *data, int data_len, int *out_len) ;

 uint8_t *HmacSha256(const uint8_t *data, int data_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *HmacSha512(const uint8_t *data, int data_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *HmacSha1(const uint8_t *data, int data_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *RandomBytes(int length, int *out_len) ;

 uint8_t *AesGcmEncrypt(const uint8_t *pt, int pt_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *AesGcmDecrypt(const uint8_t *ct, int ct_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *ChaCha20Poly1305Encrypt(const uint8_t *pt, int pt_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *ChaCha20Poly1305Decrypt(const uint8_t *ct, int ct_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *AesCbcEncrypt(const uint8_t *pt, int pt_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *AesCbcDecrypt(const uint8_t *ct, int ct_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *DesCbcEncrypt(const uint8_t *pt, int pt_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *DesCbcDecrypt(const uint8_t *ct, int ct_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *AesCtrEncrypt(const uint8_t *pt, int pt_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *AesCtrDecrypt(const uint8_t *ct, int ct_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *ChaCha20Encrypt(const uint8_t *pt, int pt_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *ChaCha20Decrypt(const uint8_t *ct, int ct_len, const uint8_t *key, int key_len, int *out_len) ;

 uint8_t *BcryptHash(const uint8_t *password, int password_len, int cost, int *out_len) ;

 uint8_t *BcryptVerify(const uint8_t *password, int password_len, const uint8_t *hash, int hash_len, int *out_len) ;

 uint8_t *Argon2idHash(const uint8_t *password, int password_len, const uint8_t *salt, int salt_len, int time_cost, int memory_cost, int parallelism, int key_len, int *out_len) ;

 uint8_t *Scrypt(const uint8_t *password, int password_len, const uint8_t *salt, int salt_len, int key_len, int *out_len) ;

 uint8_t *Pbkdf2(const uint8_t *password, int password_len, const uint8_t *salt, int salt_len, int iterations, int key_len, int *out_len) ;

 uint8_t *Hkdf(const uint8_t *ikm, int ikm_len, const uint8_t *salt, int salt_len, const uint8_t *info, int info_len, int key_len, int *out_len) ;

 uint8_t *Ed25519GenerateKey(int *out_len) ;

 uint8_t *Ed25519Sign(const uint8_t *message, int message_len, const uint8_t *private_key, int private_key_len, int *out_len) ;

 uint8_t *Ed25519Verify(const uint8_t *message, int message_len, const uint8_t *signature, int signature_len, const uint8_t *public_key, int public_key_len, int *out_len) ;

 uint8_t *RsaGenerateKey(int bits, int *out_len) ;

 uint8_t *RsaEncrypt(const uint8_t *pt, int pt_len, const uint8_t *pub_key, int pub_key_len, int *out_len) ;

 uint8_t *RsaDecrypt(const uint8_t *ct, int ct_len, const uint8_t *priv_key, int priv_key_len, int *out_len) ;

 uint8_t *RsaSign(const uint8_t *message, int message_len, const uint8_t *priv_key, int priv_key_len, int *out_len) ;

 uint8_t *RsaVerify(const uint8_t *message, int message_len, const uint8_t *signature, int signature_len, const uint8_t *pub_key, int pub_key_len, int *out_len) ;

 uint8_t *RsaPrivateKeyToPublicKey(const uint8_t *priv_key, int priv_key_len, int *out_len) ;

 uint8_t *AesXtsEncrypt(const uint8_t *pt, int pt_len, const uint8_t *key, int key_len, int64_t sector_num, int *out_len) ;

 uint8_t *AesXtsDecrypt(const uint8_t *ct, int ct_len, const uint8_t *key, int key_len, int64_t sector_num, int *out_len) ;

 uint8_t *EcdsaGenerateKey(int curve_bits, int *out_len) ;

 uint8_t *EcdsaSign(const uint8_t *message, int message_len, const uint8_t *private_key, int private_key_len, int *out_len) ;

 uint8_t *EcdsaVerify(const uint8_t *message, int message_len, const uint8_t *signature, int signature_len, const uint8_t *public_key, int public_key_len, int *out_len) ;

 uint8_t *EcdsaPrivateKeyToPublicKey(const uint8_t *private_key, int private_key_len, int *out_len) ;

 uint8_t *BlsGenerateKey(int *out_len) ;

 uint8_t *BlsPrivateKeyToPublicKey(const uint8_t *private_key, int private_key_len, int *out_len) ;

 uint8_t *BlsSign(const uint8_t *message, int message_len, const uint8_t *private_key, int private_key_len, int *out_len) ;

 uint8_t *BlsVerify(const uint8_t *message, int message_len, const uint8_t *signature, int signature_len, const uint8_t *public_key, int public_key_len, int *out_len) ;

 uint8_t *BlsAggregateSignatures(const uint8_t *signatures, int signatures_len, int count, int *out_len) ;

 uint8_t *BlsAggregatePublicKeys(const uint8_t *public_keys, int public_keys_len, int count, int *out_len) ;

/**
 * 释放 malloc 分配的缓冲区（对应 Go 版 FreeBytes）。
 * JNI 侧和 cinterop 侧都调这个。
 */
 void enc_free(uint8_t *ptr, int len) ;

#endif  /* ENCRUST_H */
